version: 2
jobs:
    shellcheck:
        docker:
            - image: nlknguyen/alpine-shellcheck:v0.4.6
        working_directory: ~/.
        steps:
            - checkout
            - run:
                name: Check Scripts
                command: |
                    ! (grep -r "stdio" . ||  grep -r "printf" . || grep -r "////" .)

workflows:
    version: 2
    workflow:
        jobs:
            - shellcheck
