version: 2
jobs:
    shellcheck:
        docker:
            - image: nlknguyen/alpine-shellcheck:v0.4.6
        working_directory: ~/.
        steps:
            - checkout
            - run:
                name: Check Scripts
                command: |
                    ! grep -r "stdio" libunit-circle ||  grep -r "printf" libunit-circle || grep -r "////" libunit-circle

workflows:
    version: 2
    workflow:
        jobs:
            - shellcheck
